version: '3.9'

networks:
  web_network:
    name: hyggeoa
    driver: bridge

services:
  hyggeoaapp:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: hyggeoaapp
    restart: always
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 4000:4000
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - web_network
